// 登录
export const USER_LOGIN = 'USER_LOGIN'
// 设置用户信息
// 所有信息
export const USER_INFO_RES = 'USER_INFO_RES'
export const USER_INFO_GETTER = 'USER_INFO_GETTER'
export const USER_INFO_SETTER = 'USER_INFO_SETTER'
// account 账户相关
export const USER_ACCOUNRT_RES = 'USER_ACCOUNRT_RES'
export const USER_ACCOUNRT_GETTER = 'USER_ACCOUNRT_GETTER'
export const USER_ACCOUNRT_SETTER = 'USER_ACCOUNRT_SETTER'
// profile 个人信息相关
export const USER_PROFILE_RES = 'USER_PROFILE_RES'
export const USER_PROFILE_GETTER = 'USER_PROFILE_GETTER'
export const USER_PROFILE_SETTER = 'USER_PROFILE_SETTER'
// bindings 绑定相关
export const USER_BINDINGS_RES = 'USER_BINDINGS_RES'
export const USER_BINDINGS_GETTER = 'USER_BINDINGS_GETTER'
export const USER_BINDINGS_SETTER = 'USER_BINDINGS_SETTER'
// loginType 登陆类型
export const USER_LOGIN_TYPE_RES = 'USER_LOGIN_TYPE_RES'
export const USER_LOGIN_TYPE_GETTER = 'USER_LOGIN_TYPE_GETTER'
export const USER_LOGIN_TYPE_SETTER = 'USER_LOGIN_TYPE_SETTER'

// Mine 个人中心  获取用户信息，歌单，收藏，mv，dj数量
export const MINE_AUTO_INFO = 'MINE_AUTO_INFO'
