// 登录
export const USER_LOGIN = 'USER_LOGIN'
// 设置用户信息
export const LOGIN_STATUS = 'LOGIN_STATUS'
export const LOGIN_STATUS_GETTERS = 'LOGIN_STATUS_GETTERS'
export const LOGIN_STATUS_SETTERS = 'LOGIN_STATUS_SETTERS'

// Mine 个人中心  获取用户信息，歌单，收藏，mv，dj数量
export const MINE_AUTO_INFO = 'MINE_AUTO_INFO'

// 获取banner轮播图信息
export const BANNER_LISTS = 'BANNER_LISTS'

/**
 * ================================
 * ==========  播放相关  ===========
 * ================================
 */
// 播放列表集合
export const PLAY_MUSIC_LISTS = 'PLAY_MUSIC_LISTS'
export const PLAY_MUSIC_LISTS_GETTERS = 'PLAY_MUSIC_LISTS_GETTERS'
export const PLAY_MUSIC_LISTS_SETTERS = 'PLAY_MUSIC_LISTS_SETTERS'

// 播放的索引信息
export const PLAY_MUSIC_INDEX = 'PLAY_MUSIC_INDEX'
export const PLAY_MUSIC_INDEX_GETTERS = 'PLAY_MUSIC_INDEX_GETTERS'
export const PLAY_MUSIC_INDEX_SETTERS = 'PLAY_MUSIC_INDEX_SETTERS'

// 播放的列表id
export const PLAY_MUSIC_LISTS_ID = 'PLAY_MUSIC_LISTS_ID'
export const PLAY_MUSIC_LISTS_ID_GETTERS = 'PLAY_MUSIC_LISTS_ID_GETTERS'
export const PLAY_MUSIC_LISTS_ID_SETTERS = 'PLAY_MUSIC_LISTS_ID_SETTERS'

// 音乐的播放状态是否在播放
export const MUSIC_IS_PLAYING = 'MUSIC_IS_PLAYING'
export const MUSIC_IS_PLAYING_GETTERS = 'MUSIC_IS_PLAYING_GETTERS'
export const MUSIC_IS_PLAYING_SETTERS = 'MUSIC_IS_PLAYING_SETTERS'

// 音乐播放的类型
export const MUSIC_PLAY_TYPE = 'MUSIC_PLAY_TYPE'
export const MUSIC_PLAY_TYPE_GETTERS = 'MUSIC_PLAY_TYPE_GETTERS'
export const MUSIC_PLAY_TYPE_SETTERS = 'MUSIC_PLAY_TYPE_SETTERS'

// 当前音乐播放的内容
export const PLAY_MUSIC_LIST = 'PLAY_MUSIC_LIST'
export const PLAY_MUSIC_LIST_SETTERS = 'PLAY_MUSIC_LIST_SETTERS'
export const PLAY_MUSIC_LIST_GETTERS = 'PLAY_MUSIC_LIST_GETTERS'

// 设置音频播放的时间
export const MUSIC_CURRENT_TIME = 'MUSIC_CURRENT_TIME'
export const MUSIC_CURRENT_TIME_GETTERS = 'MUSIC_CURRENT_TIME_GETTERS'
export const MUSIC_CURRENT_TIME_SETTERS = 'MUSIC_CURRENT_TIME_SETTERS'

// 设置音频的时长
export const MUSIC_DURATION_TIME = 'MUSIC_DURATION_TIME'
export const MUSIC_DURATION_TIME_GETTERS = 'MUSIC_DURATION_TIME_GETTERS'
export const MUSIC_DURATION_TIME_SETTERS = 'MUSIC_DURATION_TIME_SETTERS'

// 设置音频的音量大小
export const MUSIC_VOL = 'MUSIC_VOL'
export const MUSIC_VOL_GETTERS = 'MUSIC_VOL_GETTERS'
export const MUSIC_VOL_SETTERS = 'MUSIC_VOL_SETTERS'

// 正在播放的音乐的详细信息
export const MUSIC_PLAYING_DETAIL = 'MUSIC_PLAYING_DETAIL'
export const MUSIC_PLAYING_DETAIL_GETTERS = 'MUSIC_PLAYING_DETAIL_GETTERS'
export const MUSIC_PLAYING_DETAIL_SETTERS = 'MUSIC_PLAYING_DETAIL_SETTERS'

// 正在播放的音乐的专辑的近似颜色
export const MUSIC_PLAYING_COLOR = 'MUSIC_PLAYING_COLOR'
export const MUSIC_PLAYING_COLOR_GETTERS = 'MUSIC_PLAYING_COLOR_GETTERS'
export const MUSIC_PLAYING_COLOR_SETTERS = 'MUSIC_PLAYING_COLOR_SETTERS'

// 右上角菜单的显示隐藏
export const MUSIC_SHOW_FIXED_MENU = 'MUSIC_SHOW_FIXED_MENU'
export const MUSIC_SHOW_FIXED_MENU_GETTERS = 'MUSIC_SHOW_FIXED_MENU_GETTERS'
export const MUSIC_SHOW_FIXED_MENU_SETTERS = 'MUSIC_SHOW_FIXED_MENU_SETTERS'
