// 登录
export const USER_LOGIN = 'USER_LOGIN'
// 设置用户信息
// 所有信息
export const USER_INFO_RES = 'USER_INFO_RES'
export const USER_INFO_GETTER = 'USER_INFO_GETTER'
export const USER_INFO_SETTER = 'USER_INFO_SETTER'
// account 账户相关
export const USER_ACCOUNRT_RES = 'USER_ACCOUNRT_RES'
export const USER_ACCOUNRT_GETTER = 'USER_ACCOUNRT_GETTER'
export const USER_ACCOUNRT_SETTER = 'USER_ACCOUNRT_SETTER'
// profile 个人信息相关
export const USER_PROFILE_RES = 'USER_PROFILE_RES'
export const USER_PROFILE_GETTER = 'USER_PROFILE_GETTER'
export const USER_PROFILE_SETTER = 'USER_PROFILE_SETTER'
// bindings 绑定相关
export const USER_BINDINGS_RES = 'USER_BINDINGS_RES'
export const USER_BINDINGS_GETTER = 'USER_BINDINGS_GETTER'
export const USER_BINDINGS_SETTER = 'USER_BINDINGS_SETTER'
// loginType 登陆类型
export const USER_LOGIN_TYPE_RES = 'USER_LOGIN_TYPE_RES'
export const USER_LOGIN_TYPE_GETTER = 'USER_LOGIN_TYPE_GETTER'
export const USER_LOGIN_TYPE_SETTER = 'USER_LOGIN_TYPE_SETTER'

// Mine 个人中心  获取用户信息，歌单，收藏，mv，dj数量
export const MINE_AUTO_INFO = 'MINE_AUTO_INFO'

// 获取banner轮播图信息
export const BANNER_LISTS = 'BANNER_LISTS'

/**
 * ================================
 * ==========  播放相关  ===========
 * ================================
 */
// 播放列表集合
export const PLAY_MUSIC_LISTS = 'PLAY_MUSIC_LISTS'
export const PLAY_MUSIC_LISTS_GETTERS = 'PLAY_MUSIC_LISTS_GETTERS'
export const PLAY_MUSIC_LISTS_SETTERS = 'PLAY_MUSIC_LISTS_SETTERS'

// 播放的索引信息
export const PLAY_MUSIC_INDEX = 'PLAY_MUSIC_INDEX'
export const PLAY_MUSIC_INDEX_GETTERS = 'PLAY_MUSIC_INDEX_GETTERS'
export const PLAY_MUSIC_INDEX_SETTERS = 'PLAY_MUSIC_INDEX_SETTERS'

// 播放的列表id
export const PLAY_MUSIC_LISTS_ID = 'PLAY_MUSIC_LISTS_ID'
export const PLAY_MUSIC_LISTS_ID_GETTERS = 'PLAY_MUSIC_LISTS_ID_GETTERS'
export const PLAY_MUSIC_LISTS_ID_SETTERS = 'PLAY_MUSIC_LISTS_ID_SETTERS'

// 音乐的播放状态是否在播放
export const MUSIC_IS_PLAYING = 'MUSIC_IS_PLAYING'
export const MUSIC_IS_PLAYING_GETTERS = 'MUSIC_IS_PLAYING_GETTERS'
export const MUSIC_IS_PLAYING_SETTERS = 'MUSIC_IS_PLAYING_SETTERS'

// 音乐播放的类型
export const MUSIC_PLAY_TYPE = 'MUSIC_PLAY_TYPE'
export const MUSIC_PLAY_TYPE_GETTERS = 'MUSIC_PLAY_TYPE_GETTERS'
export const MUSIC_PLAY_TYPE_SETTERS = 'MUSIC_PLAY_TYPE_SETTERS'

// 当前音乐播放的内容
export const PLAY_MUSIC_LIST = 'PLAY_MUSIC_LIST'
export const PLAY_MUSIC_LIST_SETTERS = 'PLAY_MUSIC_LIST_SETTERS'
export const PLAY_MUSIC_LIST_GETTERS = 'PLAY_MUSIC_LIST_GETTERS'

// 设置音频播放的时间
export const MUSIC_CURRENT_TIME = 'MUSIC_CURRENT_TIME'
export const MUSIC_CURRENT_TIME_GETTERS = 'MUSIC_CURRENT_TIME_GETTERS'
export const MUSIC_CURRENT_TIME_SETTERS = 'MUSIC_CURRENT_TIME_SETTERS'

// 设置音频的时长
export const MUSIC_DURATION_TIME = 'MUSIC_DURATION_TIME'
export const MUSIC_DURATION_TIME_GETTERS = 'MUSIC_DURATION_TIME_GETTERS'
export const MUSIC_DURATION_TIME_SETTERS = 'MUSIC_DURATION_TIME_SETTERS'

// 设置音频的音量大小
export const MUSIC_VOL = 'MUSIC_VOL'
export const MUSIC_VOL_GETTERS = 'MUSIC_VOL_GETTERS'
export const MUSIC_VOL_SETTERS = 'MUSIC_VOL_SETTERS'
